# Website's icon url.
favicon: /images/logo.ico

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo: '/images/codingwife.png'

article:
  # Show word count and estimated reading time.
  readtime: false
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: atom-one-light

# Navigation bar menu links.
menu:
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about

# Search plugin settings.
search:
  type: insight

# Navigation bar toc settings
toc: false

# Share plugin settings.
share:
  type: sharethis
  install_url: https://platform-api.sharethis.com/js/sharethis.js#property=5d9b1ebc2b036a0011ed0d83&product=inline-share-buttons

# Comment plugin settings.
comment:
  type: gitment
  owner: leiadot
  repo: leiadot.github.io
  admin: ['leiadot']
  client_id: 51ce642a9a95d7ccdf4d
  client_secret: 6bf1657de06ee2fbaf452b4752567ab313277f50

# Other plugins and their settings.
plugins:
  mathjax: true
  katex: false
  gallery: true
  clipboard: true
  google-analytics:
    tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/leiadot
  Facebook:
    icon: fab fa-facebook
    url: https://facebook.com/CodingwifeHy2

# Links at the bottom of the page.
footer_links:
  GitHub: https://github.com/ppoffice/leiadot

author:
  email: luv.hsu@gmail.com
  picture: /images/leia.png

author_links:
  github:
    url: https://github.com/leiadot
  facebook:
    title: global.facebook
    url: https://facebook.com/CodingwifeHy2
  mail:
    url: mailto:luv.hsu@gmail.com
